<?php

class ChildClass extends BaseClass
{
	public function methodOverride()
	{
		parent::methodOverride(); // TODO: Change the autogenerated stub
	}

	public function methodToImplement()
	{
		// TODO: Implement methodToImplement() method.
	}

	protected function methodToImplement2()
	{
		// TODO: Implement methodToImplement2() method.
	}

	public function methodOverride2($param1, $param2)
	{
		parent::methodOverride2($param1, $param2); // TODO: Change the autogenerated stub
	}

	static protected function methodToImplement3()
	{
		parent::methodToImplement3(); // TODO: Change the autogenerated stub
	}


}