version: '3'
services:
  php-cli:
    image: erema/php-cli:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    tty: true
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data/sqlite/:/root/db/
    working_dir: /var/www/html