<?php

namespace pkr;

class DeckFactory
{
    public const KEY_CARD_VALUE = 'card_value';
    public const KEY_CARD_SUITE = 'card_suite';

    public const AVAILABLE_CARDS_DATA = [
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_ACE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_DEUCE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TREE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FOUR, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FIVE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SIX, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SEVEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_EIGHT, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_NINE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_JACK, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_QUEEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_KING, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_SPADES],

        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_ACE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_DEUCE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TREE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FOUR, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FIVE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SIX, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SEVEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_EIGHT, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_NINE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_JACK, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_QUEEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_KING, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_HEARTS],

        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_ACE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_DEUCE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TREE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FOUR, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FIVE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SIX, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SEVEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_EIGHT, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_NINE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_JACK, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_QUEEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_KING, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_DIAMONDS],

        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_ACE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_DEUCE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TREE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FOUR, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_FIVE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SIX, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_SEVEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_EIGHT, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_NINE, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_TEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_JACK, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_QUEEN, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS],
        [self::KEY_CARD_VALUE => Card::AVAILABLE_CARD_VALUE_KING, self::KEY_CARD_SUITE => Card::AVAILABLE_CARD_SUITE_CLUBS]

    ];

    public static function createDeck(): Deck
    {
        $cards = [];
        foreach (self::AVAILABLE_CARDS_DATA as $cardData) {
            $cards[] = new Card($cardData[self::KEY_CARD_VALUE], $cardData[self::KEY_CARD_SUITE]);
        }
        return new Deck($cards);
    }
}