<?php

namespace FileManager\Vinaigrette;

class FileManagerUnderTest extends FileManager {

    protected static function localFactoryMethod(): IFileDataObject {
        return new StubFileDataObject();// TODO: Change the autogenerated stub
    }

}