<?php
/**
 * Created by PhpStorm.
 * User: R.Yaroma
 * Date: 02.05.14
 * Time: 15:36
 */

    $photos = array(
        'М.Б. Хивук' => "hivuk.png",
        'О.Н. Сушко' => "sushko.png",
        'О.Ю. Савина' => "savina.png",
        'Н.Н. Метельская'=> "metelskaya.png",
        'Ю.Г. Кардымон' => "kardimon.png",
        'В.Э. Самосейко' => "samoseyko.png",
        'А.В. Анисимова' => "anisimova.png",
        'А.В. Волчек' => "volchyok.png",
        'Е.Ю. Бурина' => "burina.png",
        'В.Ф. Алексеева' => "alekseeva.png",
        'А.В. Недоступ' => "nedostup.png",
        'Н.А. Дубинский' => "dubinskiy.png",
        'О.И. Гасюкевич' => "gasukevich.png",
        'С.Ч. Белявский' => "belyavskiy.png",
        'Л.А. Шерснёва' => "shersneva.png",
        'А.Я. Татринова' => "tatrinova.png",
        'Н.Е. Нехай' => "nehay.png",
        'А.И. Штейнер' => "shteiner.png",
        'Д.В. Григорович' => "grigorovich.png",
        'Т.А. Тёмкина' => "temkina.png",
        'В.Н. Лемеш' => "lemesh.png",
        'А.Э. Аброскин' => "abroskin.png",
        'И.Е. Демидович' => "demidovich.png",
        'О.Н. Бортошик' => "bortoshik.png",
        'С.И. Ерошина' => "eroshina.png",
        'С.С. Семенихина' => "semenihina.png",
        'В.Л. Полторан' => "poltoran.png",
        'А.В. Жук' => "zhuk.png",
        'Ю.В. Назаренко' => "nazarenko.png",
        'Н.Г. Семижон' => "semigon.png",
        'А.А. Бурда' => "burda.png",
        'Е.Ю. Четверикова' => "chetverikova.png",
        'Л.И. Пиянзина' => "piyanzina.png",
        'Т.А. Михейчик' => "miheychyk.png",
        'В.Г. Ржеутская' => "rjeutskaya.png",
        'Л.А. Шерснева' => "shersneva.png",
        'П.В. Хроменко' => "hromenko.png",
        'Е.А. Авчинникова' => "avchinnikova.png",
        'Н.Н. Грабовская' => "grabovskaya.png",
        'В.М. Аникович' => "anikovich.png",
        'Е.В. Мурашко' => "murashko.png",
        'А.В. Черва' => "cherva.png",
        'В.В. Белокопытов' => "belokopitov.png",
        'В.М. Филиппенков' => "filippenkov.png",
        'И.А. Тихонович' => "tihonovich.png",
        'И.В. Клименков' => "klimenkov.png",
        'Е.А. Стриховская' => "strihovskaya.png",
	    'Т.А. Саханько' => "sahanko.png",
	    'О.П. Чиж' => "chiz.png",
	    'В.В. Хатько' => "hatko.png",
	    'Л.И. Пиязина' => "piyanzina.png",
	    'Н.В. Недоступ' => "nedostup.png",
	    'Д.В. Семашко' => "semashko.png",
	    'И.Е. Демилович' => "demilovich.png",
	    'И.С. Бурак' => "burak.png",
	    'Н.В. Андрейчикова' => "andreychikova.png",
	    'Д.Ю. Бирук' => "biruk.png",
	    'Е.Н. Бурак' => "burak.png",
	    'М.В. Шатило' => "shatilo.png",
		'Ю.К. Прокопенкова' => "prokopenkova.png",
		'Н.С. Хаданович' => "hadanovich.png",
		'Г.А. Худоченко' => "hudochenko.png",
		'В.В. Толкач' => "tolkach.png",
		'Н.Л. Сивец' => "sivec.png",
	);