security:
  providers:
    fetcher:
      id: other\ProjectManager\src\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      user_checker: other\ProjectManager\src\Security\UserChecker
      guard:
        authenticators: [
          other\ProjectManager\src\Security\LoginFormAuthenticator,
          other\ProjectManager\src\Security\FacebookAuthenticator
        ]
      entry_point: other\ProjectManager\src\Security\LoginFormAuthenticator
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
  access_control:
    - { path: ^/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }

