
<?php

/*
What will an opcode cache ALWAYS automatically improve?

A.
Efficiency of HTML markup generated by a PHP script

B.
Execution speed of a PHP script

C.
Memory footprint of a PHP script

D.
None of the above

E.
Running time of a loop in a PHP script

Answer: D.
None of the above

*/
echo '97. What will an opcode cache ALWAYS automatically improve?' . PHP_EOL;
echo 'None of the above' . PHP_EOL;