parameters:
    locale: 'ru'
    fromEmail: '%env(FROM_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    other\ProjectManager\src\:
        resource: '../src'
        exclude: '../src/{Entity,Migration,Kernel.php}'

    other\ProjectManager\src\Model\User\Repository\IUserRepository: '@other\ProjectManager\src\Model\User\Repository\UserRepository'
    other\ProjectManager\src\Infrastructure\Service\IFlusher: '@other\ProjectManager\src\Infrastructure\Service\Flusher'
    other\ProjectManager\src\Model\User\Service\IConfirmTokenSender: '@other\ProjectManager\src\Model\User\Service\ConfirmTokenSender'
    other\ProjectManager\src\Model\User\Service\ConfirmTokenSender:
        $from: '%fromEmail%'
    other\ProjectManager\src\Model\User\Service\ResetTokenSender:
        $from: '%fromEmail%'
    other\ProjectManager\src\Model\User\Service\ResetTokenizer:
        factory: 'other\ProjectManager\src\Infrastructure\DI\Factory\ResetTokenizerFactory::create'
        arguments:
            $interval: 'PT1H'
