<?xml version="1.0" encoding="utf-8" ?>
<defintions>

    <service name="SmsService">
        <port name="SmsServicePort" binding="tns:SmsServiceBinding">
            <soap:address location="http://gutsout.web:8080/learning/zend_cert/Data Format&amp;Types/soap/sms_service.php" />
        </port>
    </service>

    <binding name="SmsServiceBinding" type="tns:SmsServicePortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="sendSms" >
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>

</defintions>